const string = {
	common: {
		Login: "Login",
		Signup: "Sign Up",
		Phone: "Phone",
		Search: "Search",
		GoogleLogin: "Google Login",
		GoogleLogout: "Google Logout",
		FacebookLogin: "Facebook Login",
		SeeAll: "See all",
		UploadPicture: "Upload Picture",
		Camera: "Camera",
		Gallery: "Gallery",
		Update: "Update",
		Home: "Home",
		Yes: "Yes",
		No: "No",
		Cancel: "Cancel",
	},
	tabs: {
		Home: "Home",
		Explore: "Explore",
		Reservation: "Reservation",
		Profile: "Profile",
		MapView: "Map View",
		ListView: "List View",
	},
	auth: {
		Login: "Login",
		SignUp: "Sign Up",
		GetOTP: "Get OTP",
		ForgotPassword: "Forgot Password?",
		ForgotPassword0: "Please reset your password\nIf you don't remember.",
		WelcomeBack: "Welcome Back!",
		Content:
			"Find the best restaurant around you\nand get some coupons today!",
		DontHaveAccount: "Don’t have an Account?",
		BackToLogin: "Back to login?",
		SignupHere: "Sign up here",
		AlreadyHaveAccount: "Already have an Account?",
		LoginHere: "Login here",
		Email: "Email",
		Label: "Label",
		Phone_number: "Phone number",
		Password: "Password",
		Submit: "Submit",
		Forgot_password: "Forgot password?",
		ORSignInWith: "Or, Sign in with...",
		ORSignup: "Or, Sign up with email...",
		Phone: "Phone",
		CreateAccount: "Create Account",
		ContentSignup:
			"Find the best restaurant around you\nand get some coupons!",
		OTPVerification: "OTP Verification",
		VerifyPhoneReceiveCode:
			"You will receive a 4 digits code to verify your phone number",
		EnterOTPCode: "Enter OTP Code",
		EnterOTPContent: "Enter the OTP Code sent to ",
		DidntReceiveCode: "Didn't receive the Code?",
		RequestAgain: "Request again",
		ResendOTP: "Resend OTP",
		title: {
			LoginPhone: "Login with Phone",
			VerifyPhone: "Verify Phone",
			CreateAccount: "Create Account",
			Location: "Location",
			AddLocation: "Add Location",
			Category: "Category",
			Preference: "Preference",
		},
	},
	user: {
		LocationInformation: "Location information",
		PersonalInformation: "Personal information",
		First_name: "First name",
		Last_name: "Last name",
		Select_location: "Select location",
		BirthDate: "Birth Date",
		ReferralCode: "Referral Code",
		DateOfBirth: "Date of Birth",
		Continue: "Continue",
		Gender: "Gender",
		Male: "Male",
		Female: "Female",
		Prefer: "Prefer not to say",
		NonBinary: "Non-Binary",
		MyProfile: "My Profile",
		ExploreNow: "Explore Now",
		Skip: "Skip",
		SelectRestaurantCat: "Select restaurant categories",
		OneStep: "One step to go!",
		OptionGender: {
			Option1: "Male",
			Option2: "Female",
			Option3: "Prefer not to say",
			Option4: "Non-Binary",
		},
	},
	restaurant: {
		CouponsAvailable: "Coupons available",
		CouponInformations: "Coupon informations",
		AvailableCoupons: "Available coupons",
		NewRestaurants: "New restaurants",
		NewPopular: "Popular restaurants around you",
		Open: "Open",
		Close: "Close",
		AboutRestaurant: "About the restaurant",
		ViewDetail: "View Detail",
		MakeReservation: "Make Reservation",
		CallRestaurants: "Call Restaurants",
		Save: "Save",
		Menus: "Menus",
		MoreInformations: "More Informations",
		Filter: "Filter",
		ApplyFilter: "Apply Filter",
		FavoriteRestaurant: "Favorite Restaurant",
		MakeUnfavorite: "Make Unfavorite",
		MakeUnfavoriteContent:
			"Are you sure want to make unfavorite this restaurant?",
		Kms: "Km(s)",
		MaxDistance: "Max Distance",
		Deletelocation: "Delete location",
		DeletelocationContent: "Are you sure to delete this location?",
		Primarylocation: "Primary location",
		PrimarylocationConten: "Are you sure to change your primary location?",
		Pages: "Pages",
		Today: "(Today)",
		ClaimMakeReservation: "Claim & Make Reservation",
		CouponAlreadyClaimed: "Coupon Already Claimed",
		CouponNotAvailable: "Coupon Not Available",
	},
	reservation: {
		MyReservation: "My Reservation",
		ReservationDetail: "Reservation Detail",
		CreateReservation: "Create Reservation",
		ConfirmReservation: "Confirm Reservation",
		CancelReservation: "Cancel Reservation",
		TablesPeople: "Tables & No. of People",
		Upcoming_reservation_schedule: "Upcoming reservation schedule",
		Plus: "+",
		Minus: "-",
		Title: "You don’t have a reservation yet",
		Content:
			"Explore restaurant around you, make reservation with the best deal coupons!",
		SearchRestaurant: "Search Restaurant",
		DateTime: "Date & Time",
		TablesGuest: "Table & Guest Informations",
		Time: "Time",
		AvailableTime: "Available at 10am - 9 pm",
		Selected: "Selected",
		AvailableOnCoupon: "Available On Coupon",
		NotAvailable: "Not Available",
		AM: "AM",
		PM: "PM",
		VIP: "VIP",
		People: "People",
	},
	category: {
		CurratedCollection: "Currated collection",
		Categories: "Categories",
	},
	search: {
		searchPlaceholder: "Search restaurant or by location...",
	},
	invite: {
		LearnMore: "Learn more",
		Title: "Invite friends &\nGet free coupons!",
		Content:
			"Get a $25.00 discount coupon for every friend who registers on Ultimamesa using your referral code.",
	},
	imagePicker: {
		SelectAvatar: "Select Avatar",
		TakePhoto: "Take Photo...",
		ChooseFromLiberary: "Choose From Library...",
		Cancel: "Cancel",
	},
	filter: {
		OptionPrice: {
			Option1: 1,
			Option2: 2,
			Option3: 3,
			Option4: 4,
			Option5: 5,
		},
	},
	setting: {
		TitleDisance: "Preferred max distance to restaurant",
		PreferredPrice: "Preferred prices",
		SetDefaultFilter: "Set default filter",
		OptionPrice: {
			Option1: "$",
			Option2: "$$",
			Option3: "$$$",
			Option4: "$$$$",
		},
		OptionFilter: {
			Option1: "Price low - high",
			Option2: "Price high - low",
			Option3: "Closest",
		},
		Settings: "Settings",
		UserSettings: "User settings",
		AccountInformations: "Account informations",
		ChangePassword: "Change Password",
		Notifications: "Notifications",
		InviteFriend: "Invite Friend",
		DarkMode: "Dark mode",
		EnableFilter: "Enable Filter",
		MyLocation: "My Locations",
		GeneralInformations: "General Informations",
		PrivacyPolicy: "Privacy policy",
		TermsOfUse: "Terms of use",
		FAQs: "FAQs",
		AboutUltimamesa: "About Ultimamesa",
		version: "Version 1.0.0",
		LogOut: "Log out",
		DeleteAccount: "Delete Account",
		DeleteAccountMessage: "Are you sure want to delete account?",
	},
	account: {
		MyProfile: "My Profile",
		Following: "Following",
		Follower: "Follower",
		Favorite: "Favorites",
		Review: "Review",
		EditProfile: "Edit Profile",
		SaveChanges: "Save Changes",
		UpdateProfileSuccess: "Profile successfully updated",
	},
	password: {
		ChangePassword: "Change Password",
		OldPassword: "Old Password",
		NewPassword: "New Password",
		ConfirmNewPassword: "Confirm New Password",
	},
	errors: {
		type: {
			Danger: "danger",
			Success: "success",
		},
		common: {
			Alert: "Alert",
			Success: "Success",
			VerifyEmail: "Please verify your email address.",
			ForgotPassword: "Forgot Password link sent on your email.",
			TryLater: "Something went wrong! Please try later.",
			UpdatePassword: "Password updated successfully",
		},
		ClearCurrentFilter: "Are you clear your current filter",
		Required: "Required!",
		EmailInvalid: "Email is invalid",
		PasswordInvalid: "Formato de contraseña incorrecto",
		PasswordMatch: "Passwords do not match",
		PhoneInvalid: "Only numbers allow",
		MaxReferralLength: "Referral code should be 6 digit.",
		InvalidReferralLength: "Invalid referral code.",
		UserAlreadyExist: "Account is already exists.",
		LocationRedirect: "Are you want to redirect on selected location?",
	},
};

export default string;
