export const restaurants = [
    {
      'business_id': 'biz_001',
      'name': 'La Parrilla',
      'description': 'Restaurante de carnes a la parrilla',
      'category': ['restaurantes'],
      'location': { 'latitude': 19.432608, 'longitude': -99.133209 },
      'address': 'Av. Reforma 123, Ciudad de México',
      'opening_hours': { 'lunes': '9:00-22:00', 'viernes': '9:00-23:00' },
      'menu': ['T-bone steak', 'Costillas BBQ'],
      'rating': 4.7,
      'images': ['https://example.com/images/biz1.jpg'],
      'premium': true,
      'created_at': '2024-01-01T12:00:00Z',
    },
    {
      'business_id': 'biz_002',
      'name': 'Café Central',
      'description': 'Cafetería con ambiente acogedor',
      'category': ['cafeterías'],
      'location': { 'latitude': 40.712776, 'longitude': -74.005974 },
      'address': 'Main St 456, Nueva York',
      'opening_hours': { 'martes': '8:00-20:00', 'domingo': '10:00-18:00' },
      'menu': ['Capuchino', 'Croissants'],
      'rating': 4.5,
      'images': ['https://example.com/images/biz2.jpg'],
      'premium': false,
      'created_at': '2023-12-20T15:00:00Z',
    },
    {
      'business_id': 'biz_003',
      'name': 'El Bar del Sol',
      'description': 'Bar especializado en cócteles',
      'category': ['bares'],
      'location': { 'latitude': 34.052235, 'longitude': -118.243683 },
      'address': 'Sunset Blvd 789, Los Ángeles',
      'opening_hours': { 'jueves': '18:00-02:00', 'sábado': '18:00-03:00' },
      'menu': ['Margarita', 'Piña Colada'],
      'rating': 4.8,
      'images': ['https://example.com/images/biz3.jpg'],
      'premium': true,
      'created_at': '2024-01-10T18:30:00Z',
    },
    {
      'business_id': 'biz_004',
      'name': 'Teatro Central',
      'description': 'Obras de teatro clásico y moderno',
      'category': ['teatros'],
      'location': { 'latitude': 48.856613, 'longitude': 2.352222 },
      'address': 'Rue de Paris 321, París',
      'opening_hours': { 'miércoles': '14:00-22:00', 'domingo': '12:00-20:00' },
      'menu': [],
      'rating': 4.6,
      'images': ['https://example.com/images/biz4.jpg'],
      'premium': false,
      'created_at': '2024-02-01T14:00:00Z'
    },
    {
      'business_id': 'biz_005',
      'name': 'Parque Natural',
      'description': 'Parque recreativo con actividades al aire libre',
      'category': ['parques'],
      'location': { 'latitude': -33.868820, 'longitude': 151.209290 },
      'address': 'Nature St 12, Sídney',
      'opening_hours': { 'todos': '6:00-18:00' },
      'menu': [],
      'rating': 4.9,
      'images': ['https://example.com/images/biz5.jpg'],
      'premium': false,
      'created_at': '2024-02-10T08:00:00Z'
    },
  ]  